# Generated by Django 4.0.4 on 2022-06-17 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0002_neighbourhood_profile_neighbourhood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='ocuupants',
            new_name='occupants',
        ),
    ]
