# Generated by Django 4.0.4 on 2022-06-18 17:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0004_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='area_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
