# Generated by Django 4.0.4 on 2022-06-21 06:21

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0008_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='area_image',
            field=cloudinary.models.CloudinaryField(blank=True, default=True, max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='health_contact',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='police_contact',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
